// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class AbilityCustomGameTypeQueryBuilder : GraphQlQueryBuilder<AbilityCustomGameTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "id", IsComplex = true },
                new FieldMetadata { Name = "name" },
                new FieldMetadata { Name = "abilityName" },
                new FieldMetadata { Name = "language", IsComplex = true, QueryBuilderType = typeof(AbilityCustomGameLanguageTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "AbilityCustomGameType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public AbilityCustomGameTypeQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("id", alias, new GraphQlDirective[] { include, skip });
        }

        public AbilityCustomGameTypeQueryBuilder ExceptId()
        {
            return ExceptField("id");
        }

        public AbilityCustomGameTypeQueryBuilder WithName(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("name", alias, new GraphQlDirective[] { include, skip });
        }

        public AbilityCustomGameTypeQueryBuilder ExceptName()
        {
            return ExceptField("name");
        }

        public AbilityCustomGameTypeQueryBuilder WithAbilityName(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("abilityName", alias, new GraphQlDirective[] { include, skip });
        }

        public AbilityCustomGameTypeQueryBuilder ExceptAbilityName()
        {
            return ExceptField("abilityName");
        }

        public AbilityCustomGameTypeQueryBuilder WithLanguage(AbilityCustomGameLanguageTypeQueryBuilder abilityCustomGameLanguageTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("language", alias, abilityCustomGameLanguageTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public AbilityCustomGameTypeQueryBuilder ExceptLanguage()
        {
            return ExceptField("language");
        }
    }
}
