// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroItemPurchaseObjectType
    {
        public int? ItemId { get; set; }
        public int? Instance { get; set; }
        public long? Time { get; set; }
        public long? Count { get; set; }
        public long? Wins { get; set; }
        public decimal? WinsAverage { get; set; }
    }
}
