// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum LeagueRegion
    {
        [EnumMember(Value = "UNSET")] Unset,
        [EnumMember(Value = "NA")] Na,
        [EnumMember(Value = "SA")] Sa,
        [EnumMember(Value = "EUROPE")] Europe,
        [EnumMember(Value = "CIS")] Cis,
        [EnumMember(Value = "CHINA")] China,
        [EnumMember(Value = "SEA")] Sea
    }
}
