// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchReplayUploadStatsTypeQueryBuilder : GraphQlQueryBuilder<MatchReplayUploadStatsTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "spectators", IsComplex = true },
                new FieldMetadata { Name = "pickBans", IsComplex = true, QueryBuilderType = typeof(MatchReplayUploadPickBanTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "MatchReplayUploadStatsType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public MatchReplayUploadStatsTypeQueryBuilder WithSpectators(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("spectators", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchReplayUploadStatsTypeQueryBuilder ExceptSpectators()
        {
            return ExceptField("spectators");
        }

        public MatchReplayUploadStatsTypeQueryBuilder WithPickBans(MatchReplayUploadPickBanTypeQueryBuilder matchReplayUploadPickBanTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("pickBans", alias, matchReplayUploadPickBanTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public MatchReplayUploadStatsTypeQueryBuilder ExceptPickBans()
        {
            return ExceptField("pickBans");
        }
    }
}
