// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerStatsDeathEventType
    {
        public int? Time { get; set; }
        public short? Attacker { get; set; }
        public int? Target { get; set; }
        public int? ByAbility { get; set; }
        public int? ByItem { get; set; }
        public int? GoldFed { get; set; }
        public int? XpFed { get; set; }
        public int? TimeDead { get; set; }
        public int? PositionX { get; set; }
        public int? PositionY { get; set; }
        public int? GoldLost { get; set; }
        public IList<object> Assist { get; set; }
        public bool? IsWardWalkThrough { get; set; }
        public bool? IsAttemptTpOut { get; set; }
        public bool? IsDieBack { get; set; }
        public bool? IsBurst { get; set; }
        public bool? IsEngagedOnDeath { get; set; }
        public bool? HasHealAvailable { get; set; }
        public bool? IsTracked { get; set; }
    }
}
