// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerAdditionalUnitType
    {
        public short? Item0Id { get; set; }
        public short? Item1Id { get; set; }
        public short? Item2Id { get; set; }
        public short? Item3Id { get; set; }
        public short? Item4Id { get; set; }
        public short? Item5Id { get; set; }
        public short? Backpack0Id { get; set; }
        public short? Backpack1Id { get; set; }
        public short? Backpack2Id { get; set; }
        public short? Neutral0Id { get; set; }
    }
}
