// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PageLeaguesQueryQueryBuilder : GraphQlQueryBuilder<PageLeaguesQueryQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "dpcPositionStats", IsComplex = true, QueryBuilderType = typeof(LeagueDpcPositionStatObjectTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "PageLeaguesQuery"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public PageLeaguesQueryQueryBuilder WithDpcPositionStats(LeagueDpcPositionStatObjectTypeQueryBuilder leagueDpcPositionStatObjectTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("dpcPositionStats", alias, leagueDpcPositionStatObjectTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public PageLeaguesQueryQueryBuilder ExceptDpcPositionStats()
        {
            return ExceptField("dpcPositionStats");
        }
    }
}
