// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum PlayerBehaviorActivity
    {
        [EnumMember(Value = "NONE")] None,
        [EnumMember(Value = "VERY_LOW")] VeryLow,
        [EnumMember(Value = "LOW")] Low,
        [EnumMember(Value = "MEDIUM")] Medium,
        [EnumMember(Value = "HIGH")] High,
        [EnumMember(Value = "VERY_HIGH")] VeryHigh,
        [EnumMember(Value = "INTENSE")] Intense
    }
}
