// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class SpiritBearInventoryType
    {
        public int? Time { get; set; }
        public SpiritBearInventoryObjectType Item0 { get; set; }
        public SpiritBearInventoryObjectType Item1 { get; set; }
        public SpiritBearInventoryObjectType Item2 { get; set; }
        public SpiritBearInventoryObjectType Item3 { get; set; }
        public SpiritBearInventoryObjectType Item4 { get; set; }
        public SpiritBearInventoryObjectType Item5 { get; set; }
        public SpiritBearInventoryObjectType BackPack0 { get; set; }
        public SpiritBearInventoryObjectType BackPack1 { get; set; }
        public SpiritBearInventoryObjectType BackPack2 { get; set; }
        public SpiritBearInventoryObjectType Teleport0 { get; set; }
        public SpiritBearInventoryObjectType Neutral0 { get; set; }
    }
}
