// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class SteamAccountSeasonActiveLeaderboardRankType
    {
        public long? SteamAccountId { get; set; }
        public SteamAccountType SteamAccount { get; set; }
        public short? AvgImp { get; set; }
        public LeaderboardDivision? DivisionId { get; set; }
        public long? LastUpdateDateTime { get; set; }
        public short? MatchCount { get; set; }
        public MatchPlayerPositionType? Position { get; set; }
        public byte? PositionValue { get; set; }
        public short? Rank { get; set; }
        public short? RankShift { get; set; }
        public short? TopHeroOne { get; set; }
        public short? TopHeroTwo { get; set; }
        public short? TopHeroThree { get; set; }
        public byte? WinRate { get; set; }
    }
}
