// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum AbilityDispellEnum
    {
        [EnumMember(Value = "NONE")] None,
        [EnumMember(Value = "NO")] No,
        [EnumMember(Value = "YES")] Yes,
        [EnumMember(Value = "YES_STRONG")] YesStrong
    }
}
