// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class AbilityLanguageType
    {
        public string DisplayName { get; set; }
        public IList<string> Description { get; set; }
        public IList<string> Attributes { get; set; }
        public string Lore { get; set; }
        public string AghanimDescription { get; set; }
        public string ShardDescription { get; set; }
        public IList<string> Notes { get; set; }
    }
}
