// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class CaptainJackIdentityProfileUpdateRequestType : IGraphQlInputObject
    {
        private InputPropertyInfo _email;
        private InputPropertyInfo _feedLevel;
        private InputPropertyInfo _emailLevel;
        private InputPropertyInfo _dailyEmail;
        private InputPropertyInfo _weeklyEmail;
        private InputPropertyInfo _monthlyEmail;
        private InputPropertyInfo _proCircuitFeedLevel;
        private InputPropertyInfo _proCircuitEmailLevel;
        private InputPropertyInfo _themeType;
        private InputPropertyInfo _language;
        private InputPropertyInfo _emailHour;
        private InputPropertyInfo _isStratzPublic;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        public QueryBuilderParameter<string> Email
        {
            get { return (QueryBuilderParameter<string>)_email.Value; }
            set { _email = new InputPropertyInfo { Name = "email", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<byte?>))]
        #endif
        public QueryBuilderParameter<byte?> FeedLevel
        {
            get { return (QueryBuilderParameter<byte?>)_feedLevel.Value; }
            set { _feedLevel = new InputPropertyInfo { Name = "feedLevel", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<byte?>))]
        #endif
        public QueryBuilderParameter<byte?> EmailLevel
        {
            get { return (QueryBuilderParameter<byte?>)_emailLevel.Value; }
            set { _emailLevel = new InputPropertyInfo { Name = "emailLevel", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        public QueryBuilderParameter<bool?> DailyEmail
        {
            get { return (QueryBuilderParameter<bool?>)_dailyEmail.Value; }
            set { _dailyEmail = new InputPropertyInfo { Name = "dailyEmail", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        public QueryBuilderParameter<bool?> WeeklyEmail
        {
            get { return (QueryBuilderParameter<bool?>)_weeklyEmail.Value; }
            set { _weeklyEmail = new InputPropertyInfo { Name = "weeklyEmail", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        public QueryBuilderParameter<bool?> MonthlyEmail
        {
            get { return (QueryBuilderParameter<bool?>)_monthlyEmail.Value; }
            set { _monthlyEmail = new InputPropertyInfo { Name = "monthlyEmail", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<byte?>))]
        #endif
        public QueryBuilderParameter<byte?> ProCircuitFeedLevel
        {
            get { return (QueryBuilderParameter<byte?>)_proCircuitFeedLevel.Value; }
            set { _proCircuitFeedLevel = new InputPropertyInfo { Name = "proCircuitFeedLevel", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<byte?>))]
        #endif
        public QueryBuilderParameter<byte?> ProCircuitEmailLevel
        {
            get { return (QueryBuilderParameter<byte?>)_proCircuitEmailLevel.Value; }
            set { _proCircuitEmailLevel = new InputPropertyInfo { Name = "proCircuitEmailLevel", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<byte?>))]
        #endif
        public QueryBuilderParameter<byte?> ThemeType
        {
            get { return (QueryBuilderParameter<byte?>)_themeType.Value; }
            set { _themeType = new InputPropertyInfo { Name = "themeType", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<Language?>))]
        #endif
        public QueryBuilderParameter<Language?> Language
        {
            get { return (QueryBuilderParameter<Language?>)_language.Value; }
            set { _language = new InputPropertyInfo { Name = "language", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<byte?>))]
        #endif
        public QueryBuilderParameter<byte?> EmailHour
        {
            get { return (QueryBuilderParameter<byte?>)_emailHour.Value; }
            set { _emailHour = new InputPropertyInfo { Name = "emailHour", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonConverter(typeof(QueryBuilderParameterConverter<bool?>))]
        #endif
        public QueryBuilderParameter<bool?> IsStratzPublic
        {
            get { return (QueryBuilderParameter<bool?>)_isStratzPublic.Value; }
            set { _isStratzPublic = new InputPropertyInfo { Name = "isStratzPublic", Value = value }; }
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_email.Name != null) yield return _email;
            if (_feedLevel.Name != null) yield return _feedLevel;
            if (_emailLevel.Name != null) yield return _emailLevel;
            if (_dailyEmail.Name != null) yield return _dailyEmail;
            if (_weeklyEmail.Name != null) yield return _weeklyEmail;
            if (_monthlyEmail.Name != null) yield return _monthlyEmail;
            if (_proCircuitFeedLevel.Name != null) yield return _proCircuitFeedLevel;
            if (_proCircuitEmailLevel.Name != null) yield return _proCircuitEmailLevel;
            if (_themeType.Name != null) yield return _themeType;
            if (_language.Name != null) yield return _language;
            if (_emailHour.Name != null) yield return _emailHour;
            if (_isStratzPublic.Name != null) yield return _isStratzPublic;
        }
    }
}
