// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class DotaMutation
    {
        public YogurtMutation Yogurt { get; set; }
        public DotaUserMutation User { get; set; }
        public AdminMutation Admin { get; set; }
        public bool? RetryMatchDownload { get; set; }
    }
}
