// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroPositionTimeDetailTypeQueryBuilder : GraphQlQueryBuilder<HeroPositionTimeDetailTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "heroId", IsComplex = true },
                new FieldMetadata { Name = "week" },
                new FieldMetadata { Name = "time" },
                new FieldMetadata { Name = "position" },
                new FieldMetadata { Name = "bracketBasicIds" },
                new FieldMetadata { Name = "matchCount", IsComplex = true },
                new FieldMetadata { Name = "remainingMatchCount", IsComplex = true },
                new FieldMetadata { Name = "winCount", IsComplex = true },
                new FieldMetadata { Name = "mvp", IsComplex = true },
                new FieldMetadata { Name = "topCore", IsComplex = true },
                new FieldMetadata { Name = "topSupport", IsComplex = true },
                new FieldMetadata { Name = "courierKills", IsComplex = true },
                new FieldMetadata { Name = "apm", IsComplex = true },
                new FieldMetadata { Name = "casts", IsComplex = true },
                new FieldMetadata { Name = "abilityCasts", IsComplex = true },
                new FieldMetadata { Name = "kills", IsComplex = true },
                new FieldMetadata { Name = "deaths", IsComplex = true },
                new FieldMetadata { Name = "assists", IsComplex = true },
                new FieldMetadata { Name = "networth", IsComplex = true },
                new FieldMetadata { Name = "xp", IsComplex = true },
                new FieldMetadata { Name = "cs", IsComplex = true },
                new FieldMetadata { Name = "dn", IsComplex = true },
                new FieldMetadata { Name = "neutrals", IsComplex = true },
                new FieldMetadata { Name = "heroDamage", IsComplex = true },
                new FieldMetadata { Name = "towerDamage", IsComplex = true },
                new FieldMetadata { Name = "physicalDamage", IsComplex = true },
                new FieldMetadata { Name = "magicalDamage", IsComplex = true },
                new FieldMetadata { Name = "physicalDamageReceived", IsComplex = true },
                new FieldMetadata { Name = "magicalDamageReceived", IsComplex = true },
                new FieldMetadata { Name = "tripleKill", IsComplex = true },
                new FieldMetadata { Name = "ultraKill", IsComplex = true },
                new FieldMetadata { Name = "rampage", IsComplex = true },
                new FieldMetadata { Name = "godLike", IsComplex = true },
                new FieldMetadata { Name = "goldPerMinute", IsComplex = true },
                new FieldMetadata { Name = "disableCount", IsComplex = true },
                new FieldMetadata { Name = "disableDuration", IsComplex = true },
                new FieldMetadata { Name = "stunCount", IsComplex = true },
                new FieldMetadata { Name = "stunDuration", IsComplex = true },
                new FieldMetadata { Name = "slowCount", IsComplex = true },
                new FieldMetadata { Name = "slowDuration", IsComplex = true },
                new FieldMetadata { Name = "healingSelf", IsComplex = true },
                new FieldMetadata { Name = "healingAllies", IsComplex = true },
                new FieldMetadata { Name = "invisibleCount", IsComplex = true },
                new FieldMetadata { Name = "runePower", IsComplex = true },
                new FieldMetadata { Name = "runeBounty", IsComplex = true },
                new FieldMetadata { Name = "level", IsComplex = true },
                new FieldMetadata { Name = "campsStacked", IsComplex = true },
                new FieldMetadata { Name = "supportGold", IsComplex = true },
                new FieldMetadata { Name = "purgeModifiers", IsComplex = true },
                new FieldMetadata { Name = "ancients", IsComplex = true },
                new FieldMetadata { Name = "teamKills", IsComplex = true },
                new FieldMetadata { Name = "goldLost", IsComplex = true },
                new FieldMetadata { Name = "goldFed", IsComplex = true },
                new FieldMetadata { Name = "buybackCount", IsComplex = true },
                new FieldMetadata { Name = "weakenCount", IsComplex = true },
                new FieldMetadata { Name = "weakenDuration", IsComplex = true },
                new FieldMetadata { Name = "physicalItemDamage", IsComplex = true },
                new FieldMetadata { Name = "magicalItemDamage", IsComplex = true },
                new FieldMetadata { Name = "healingItemSelf", IsComplex = true },
                new FieldMetadata { Name = "healingItemAllies", IsComplex = true },
                new FieldMetadata { Name = "xpFed", IsComplex = true },
                new FieldMetadata { Name = "pureDamageReceived", IsComplex = true },
                new FieldMetadata { Name = "attackDamage", IsComplex = true },
                new FieldMetadata { Name = "attackCount", IsComplex = true },
                new FieldMetadata { Name = "castDamage", IsComplex = true },
                new FieldMetadata { Name = "damageReceived", IsComplex = true },
                new FieldMetadata { Name = "damage", IsComplex = true },
                new FieldMetadata { Name = "pureDamage", IsComplex = true },
                new FieldMetadata { Name = "kDAAverage", IsComplex = true },
                new FieldMetadata { Name = "killContributionAverage", IsComplex = true },
                new FieldMetadata { Name = "stompWon", IsComplex = true },
                new FieldMetadata { Name = "stompLost", IsComplex = true },
                new FieldMetadata { Name = "comeBackWon", IsComplex = true },
                new FieldMetadata { Name = "comeBackLost", IsComplex = true }
            };

        protected override string TypeName { get { return "HeroPositionTimeDetailType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public HeroPositionTimeDetailTypeQueryBuilder WithHeroId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("heroId", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptHeroId()
        {
            return ExceptField("heroId");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithWeek(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("week", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptWeek()
        {
            return ExceptField("week");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithTime(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("time", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptTime()
        {
            return ExceptField("time");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPosition(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("position", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPosition()
        {
            return ExceptField("position");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithBracketBasicIds(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("bracketBasicIds", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptBracketBasicIds()
        {
            return ExceptField("bracketBasicIds");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithMatchCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("matchCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptMatchCount()
        {
            return ExceptField("matchCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithRemainingMatchCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("remainingMatchCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptRemainingMatchCount()
        {
            return ExceptField("remainingMatchCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithWinCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("winCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptWinCount()
        {
            return ExceptField("winCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithMvp(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("mvp", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptMvp()
        {
            return ExceptField("mvp");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithTopCore(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("topCore", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptTopCore()
        {
            return ExceptField("topCore");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithTopSupport(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("topSupport", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptTopSupport()
        {
            return ExceptField("topSupport");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithCourierKills(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("courierKills", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptCourierKills()
        {
            return ExceptField("courierKills");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithApm(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("apm", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptApm()
        {
            return ExceptField("apm");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithCasts(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("casts", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptCasts()
        {
            return ExceptField("casts");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithAbilityCasts(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("abilityCasts", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptAbilityCasts()
        {
            return ExceptField("abilityCasts");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithKills(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("kills", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptKills()
        {
            return ExceptField("kills");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithDeaths(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("deaths", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptDeaths()
        {
            return ExceptField("deaths");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithAssists(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("assists", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptAssists()
        {
            return ExceptField("assists");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithNetworth(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("networth", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptNetworth()
        {
            return ExceptField("networth");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithXp(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("xp", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptXp()
        {
            return ExceptField("xp");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithCs(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("cs", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptCs()
        {
            return ExceptField("cs");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithDn(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("dn", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptDn()
        {
            return ExceptField("dn");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithNeutrals(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("neutrals", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptNeutrals()
        {
            return ExceptField("neutrals");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithHeroDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("heroDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptHeroDamage()
        {
            return ExceptField("heroDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithTowerDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("towerDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptTowerDamage()
        {
            return ExceptField("towerDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPhysicalDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("physicalDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPhysicalDamage()
        {
            return ExceptField("physicalDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithMagicalDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("magicalDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptMagicalDamage()
        {
            return ExceptField("magicalDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPhysicalDamageReceived(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("physicalDamageReceived", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPhysicalDamageReceived()
        {
            return ExceptField("physicalDamageReceived");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithMagicalDamageReceived(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("magicalDamageReceived", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptMagicalDamageReceived()
        {
            return ExceptField("magicalDamageReceived");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithTripleKill(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("tripleKill", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptTripleKill()
        {
            return ExceptField("tripleKill");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithUltraKill(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("ultraKill", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptUltraKill()
        {
            return ExceptField("ultraKill");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithRampage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("rampage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptRampage()
        {
            return ExceptField("rampage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithGodLike(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("godLike", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptGodLike()
        {
            return ExceptField("godLike");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithGoldPerMinute(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("goldPerMinute", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptGoldPerMinute()
        {
            return ExceptField("goldPerMinute");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithDisableCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("disableCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptDisableCount()
        {
            return ExceptField("disableCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithDisableDuration(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("disableDuration", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptDisableDuration()
        {
            return ExceptField("disableDuration");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithStunCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("stunCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptStunCount()
        {
            return ExceptField("stunCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithStunDuration(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("stunDuration", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptStunDuration()
        {
            return ExceptField("stunDuration");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithSlowCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("slowCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptSlowCount()
        {
            return ExceptField("slowCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithSlowDuration(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("slowDuration", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptSlowDuration()
        {
            return ExceptField("slowDuration");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithHealingSelf(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("healingSelf", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptHealingSelf()
        {
            return ExceptField("healingSelf");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithHealingAllies(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("healingAllies", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptHealingAllies()
        {
            return ExceptField("healingAllies");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithInvisibleCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("invisibleCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptInvisibleCount()
        {
            return ExceptField("invisibleCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithRunePower(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("runePower", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptRunePower()
        {
            return ExceptField("runePower");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithRuneBounty(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("runeBounty", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptRuneBounty()
        {
            return ExceptField("runeBounty");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithLevel(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("level", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptLevel()
        {
            return ExceptField("level");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithCampsStacked(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("campsStacked", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptCampsStacked()
        {
            return ExceptField("campsStacked");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithSupportGold(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("supportGold", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptSupportGold()
        {
            return ExceptField("supportGold");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPurgeModifiers(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("purgeModifiers", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPurgeModifiers()
        {
            return ExceptField("purgeModifiers");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithAncients(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("ancients", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptAncients()
        {
            return ExceptField("ancients");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithTeamKills(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("teamKills", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptTeamKills()
        {
            return ExceptField("teamKills");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithGoldLost(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("goldLost", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptGoldLost()
        {
            return ExceptField("goldLost");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithGoldFed(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("goldFed", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptGoldFed()
        {
            return ExceptField("goldFed");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithBuybackCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("buybackCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptBuybackCount()
        {
            return ExceptField("buybackCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithWeakenCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("weakenCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptWeakenCount()
        {
            return ExceptField("weakenCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithWeakenDuration(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("weakenDuration", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptWeakenDuration()
        {
            return ExceptField("weakenDuration");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPhysicalItemDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("physicalItemDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPhysicalItemDamage()
        {
            return ExceptField("physicalItemDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithMagicalItemDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("magicalItemDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptMagicalItemDamage()
        {
            return ExceptField("magicalItemDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithHealingItemSelf(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("healingItemSelf", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptHealingItemSelf()
        {
            return ExceptField("healingItemSelf");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithHealingItemAllies(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("healingItemAllies", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptHealingItemAllies()
        {
            return ExceptField("healingItemAllies");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithXpFed(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("xpFed", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptXpFed()
        {
            return ExceptField("xpFed");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPureDamageReceived(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("pureDamageReceived", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPureDamageReceived()
        {
            return ExceptField("pureDamageReceived");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithAttackDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("attackDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptAttackDamage()
        {
            return ExceptField("attackDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithAttackCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("attackCount", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptAttackCount()
        {
            return ExceptField("attackCount");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithCastDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("castDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptCastDamage()
        {
            return ExceptField("castDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithDamageReceived(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("damageReceived", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptDamageReceived()
        {
            return ExceptField("damageReceived");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("damage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptDamage()
        {
            return ExceptField("damage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithPureDamage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("pureDamage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptPureDamage()
        {
            return ExceptField("pureDamage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithKdaAverage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("kDAAverage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptKdaAverage()
        {
            return ExceptField("kDAAverage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithKillContributionAverage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("killContributionAverage", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptKillContributionAverage()
        {
            return ExceptField("killContributionAverage");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithStompWon(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("stompWon", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptStompWon()
        {
            return ExceptField("stompWon");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithStompLost(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("stompLost", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptStompLost()
        {
            return ExceptField("stompLost");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithComeBackWon(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("comeBackWon", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptComeBackWon()
        {
            return ExceptField("comeBackWon");
        }

        public HeroPositionTimeDetailTypeQueryBuilder WithComeBackLost(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("comeBackLost", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailTypeQueryBuilder ExceptComeBackLost()
        {
            return ExceptField("comeBackLost");
        }
    }
}
