// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroPurchasePatternTypeQueryBuilder : GraphQlQueryBuilder<HeroPurchasePatternTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "startingItems", IsComplex = true, QueryBuilderType = typeof(HeroItemStartingPurchaseTypeQueryBuilder) },
                new FieldMetadata { Name = "earlyGame", IsComplex = true, QueryBuilderType = typeof(HeroItemPurchaseTypeQueryBuilder) },
                new FieldMetadata { Name = "midGame", IsComplex = true, QueryBuilderType = typeof(HeroItemPurchaseTypeQueryBuilder) },
                new FieldMetadata { Name = "lateGame", IsComplex = true, QueryBuilderType = typeof(HeroItemPurchaseTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "HeroPurchasePatternType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public HeroPurchasePatternTypeQueryBuilder WithStartingItems(HeroItemStartingPurchaseTypeQueryBuilder heroItemStartingPurchaseTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("startingItems", alias, heroItemStartingPurchaseTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public HeroPurchasePatternTypeQueryBuilder ExceptStartingItems()
        {
            return ExceptField("startingItems");
        }

        public HeroPurchasePatternTypeQueryBuilder WithEarlyGame(HeroItemPurchaseTypeQueryBuilder heroItemPurchaseTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("earlyGame", alias, heroItemPurchaseTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public HeroPurchasePatternTypeQueryBuilder ExceptEarlyGame()
        {
            return ExceptField("earlyGame");
        }

        public HeroPurchasePatternTypeQueryBuilder WithMidGame(HeroItemPurchaseTypeQueryBuilder heroItemPurchaseTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("midGame", alias, heroItemPurchaseTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public HeroPurchasePatternTypeQueryBuilder ExceptMidGame()
        {
            return ExceptField("midGame");
        }

        public HeroPurchasePatternTypeQueryBuilder WithLateGame(HeroItemPurchaseTypeQueryBuilder heroItemPurchaseTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("lateGame", alias, heroItemPurchaseTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public HeroPurchasePatternTypeQueryBuilder ExceptLateGame()
        {
            return ExceptField("lateGame");
        }
    }
}
