// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroPositionTimeDetailAverageTypeQueryBuilder : GraphQlQueryBuilder<HeroPositionTimeDetailAverageTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "heroId", IsComplex = true },
                new FieldMetadata { Name = "week" },
                new FieldMetadata { Name = "bracketBasicIds" },
                new FieldMetadata { Name = "position" },
                new FieldMetadata { Name = "events", IsComplex = true, QueryBuilderType = typeof(HeroPositionTimeDetailAverageObjectTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "HeroPositionTimeDetailAverageType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public HeroPositionTimeDetailAverageTypeQueryBuilder WithHeroId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("heroId", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder ExceptHeroId()
        {
            return ExceptField("heroId");
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder WithWeek(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("week", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder ExceptWeek()
        {
            return ExceptField("week");
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder WithBracketBasicIds(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("bracketBasicIds", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder ExceptBracketBasicIds()
        {
            return ExceptField("bracketBasicIds");
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder WithPosition(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("position", alias, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder ExceptPosition()
        {
            return ExceptField("position");
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder WithEvents(HeroPositionTimeDetailAverageObjectTypeQueryBuilder heroPositionTimeDetailAverageObjectTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("events", alias, heroPositionTimeDetailAverageObjectTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public HeroPositionTimeDetailAverageTypeQueryBuilder ExceptEvents()
        {
            return ExceptField("events");
        }
    }
}
