// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum HeroPrimaryAttributeType
    {
        [EnumMember(Value = "STR")] Str,
        [EnumMember(Value = "AGI")] Agi,
        [EnumMember(Value = "INT")] Int,
        [EnumMember(Value = "ALL")] All
    }
}
