// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroItemBootPurchaseType
    {
        public int? HeroId { get; set; }
        public int? Week { get; set; }
        public RankBracketHeroTimeDetail? BracketBasic { get; set; }
        public MatchPlayerPositionType? Position { get; set; }
        public IList<HeroItemBootPurchaseObjectType> Events { get; set; }
        public long? Count { get; set; }
    }
}
