// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum HeroRoleEnum
    {
        [EnumMember(Value = "CARRY")] Carry,
        [EnumMember(Value = "ESCAPE")] Escape,
        [EnumMember(Value = "NUKER")] Nuker,
        [EnumMember(Value = "INITIATOR")] Initiator,
        [EnumMember(Value = "DURABLE")] Durable,
        [EnumMember(Value = "DISABLER")] Disabler,
        [EnumMember(Value = "JUNGLER")] Jungler,
        [EnumMember(Value = "SUPPORT")] Support,
        [EnumMember(Value = "PUSHER")] Pusher
    }
}
