// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroPurchasePatternType
    {
        public HeroItemStartingPurchaseType StartingItems { get; set; }
        public HeroItemPurchaseType EarlyGame { get; set; }
        public HeroItemPurchaseType MidGame { get; set; }
        public HeroItemPurchaseType LateGame { get; set; }
    }
}
