// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class HeroPositionTimeDetailAverageObjectType
    {
        public int? Time { get; set; }
        public long? MatchCount { get; set; }
        public long? RemainingMatchCount { get; set; }
        public long? WinCount { get; set; }
        public decimal? Mvp { get; set; }
        public decimal? TopCore { get; set; }
        public decimal? TopSupport { get; set; }
        public decimal? CourierKills { get; set; }
        public decimal? Apm { get; set; }
        public decimal? Casts { get; set; }
        public decimal? AbilityCasts { get; set; }
        public decimal? Kills { get; set; }
        public decimal? Deaths { get; set; }
        public decimal? Assists { get; set; }
        public decimal? Networth { get; set; }
        public decimal? Xp { get; set; }
        public decimal? Cs { get; set; }
        public decimal? Dn { get; set; }
        public decimal? Neutrals { get; set; }
        public decimal? HeroDamage { get; set; }
        public decimal? TowerDamage { get; set; }
        public decimal? PhysicalDamage { get; set; }
        public decimal? MagicalDamage { get; set; }
        public decimal? PhysicalDamageReceived { get; set; }
        public decimal? MagicalDamageReceived { get; set; }
        public decimal? TripleKill { get; set; }
        public decimal? UltraKill { get; set; }
        public decimal? Rampage { get; set; }
        public decimal? GodLike { get; set; }
        public decimal? DisableCount { get; set; }
        public decimal? DisableDuration { get; set; }
        public decimal? StunCount { get; set; }
        public decimal? StunDuration { get; set; }
        public decimal? SlowCount { get; set; }
        public decimal? SlowDuration { get; set; }
        public decimal? HealingSelf { get; set; }
        public decimal? HealingAllies { get; set; }
        public decimal? InvisibleCount { get; set; }
        public decimal? RunePower { get; set; }
        public decimal? RuneBounty { get; set; }
        public decimal? Level { get; set; }
        public decimal? CampsStacked { get; set; }
        public decimal? SupportGold { get; set; }
        public decimal? PurgeModifiers { get; set; }
        public decimal? Ancients { get; set; }
        public decimal? TeamKills { get; set; }
        public decimal? GoldLost { get; set; }
        public decimal? GoldFed { get; set; }
        public decimal? BuybackCount { get; set; }
        public decimal? WeakenCount { get; set; }
        public decimal? WeakenDuration { get; set; }
        public decimal? PhysicalItemDamage { get; set; }
        public decimal? MagicalItemDamage { get; set; }
        public decimal? HealingItemSelf { get; set; }
        public decimal? HealingItemAllies { get; set; }
        public decimal? XpFed { get; set; }
        public decimal? PureDamageReceived { get; set; }
        public decimal? AttackDamage { get; set; }
        public decimal? CastDamage { get; set; }
        public decimal? DamageReceived { get; set; }
        public decimal? Damage { get; set; }
        public decimal? PureDamage { get; set; }
        public decimal? KdaAverage { get; set; }
        public decimal? KillContributionAverage { get; set; }
        public decimal? StompWon { get; set; }
        public decimal? StompLost { get; set; }
        public decimal? ComeBackWon { get; set; }
        public decimal? ComeBackLost { get; set; }
    }
}
