// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum LeagueNodeDefaultGroupEnum
    {
        [EnumMember(Value = "INVALID")] Invalid,
        [EnumMember(Value = "BEST_OF_ONE")] BestOfOne,
        [EnumMember(Value = "BEST_OF_THREE")] BestOfThree,
        [EnumMember(Value = "BEST_OF_FIVE")] BestOfFive,
        [EnumMember(Value = "BEST_OF_TWO")] BestOfTwo
    }
}
