// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class LeagueMetaType
    {
        public int? LeagueId { get; set; }
        public LeagueMetaDetailType BestRecord { get; set; }
        public LeagueMetaDetailType MostPicked { get; set; }
        public LeagueMetaDetailType MostBanned { get; set; }
        public int? MissingMatchCount { get; set; }
        public int? TotalMatchCount { get; set; }
        public LeagueType League { get; set; }
    }
}
