// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class LiveEventMatchDireTideStompTypeQueryBuilder : GraphQlQueryBuilder<LiveEventMatchDireTideStompTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "match", IsComplex = true, QueryBuilderType = typeof(DireTideCustomGameMatchTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "LiveEventMatchDireTideStompType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public LiveEventMatchDireTideStompTypeQueryBuilder WithMatch(DireTideCustomGameMatchTypeQueryBuilder direTideCustomGameMatchTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("match", alias, direTideCustomGameMatchTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public LiveEventMatchDireTideStompTypeQueryBuilder ExceptMatch()
        {
            return ExceptField("match");
        }
    }
}
