// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder : GraphQlQueryBuilder<MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "id" },
                new FieldMetadata { Name = "count" },
                new FieldMetadata { Name = "gold" },
                new FieldMetadata { Name = "xp" }
            };

        protected override string TypeName { get { return "MatchPlayerStatsFarmDistributionObjectType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("id", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder ExceptId()
        {
            return ExceptField("id");
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder WithCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("count", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder ExceptCount()
        {
            return ExceptField("count");
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder WithGold(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("gold", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder ExceptGold()
        {
            return ExceptField("gold");
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder WithXp(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("xp", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsFarmDistributionObjectTypeQueryBuilder ExceptXp()
        {
            return ExceptField("xp");
        }
    }
}
