// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchPlayerStatsAllTalkEventTypeQueryBuilder : GraphQlQueryBuilder<MatchPlayerStatsAllTalkEventTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "time" },
                new FieldMetadata { Name = "message" },
                new FieldMetadata { Name = "pausedTick" }
            };

        protected override string TypeName { get { return "MatchPlayerStatsAllTalkEventType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public MatchPlayerStatsAllTalkEventTypeQueryBuilder WithTime(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("time", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsAllTalkEventTypeQueryBuilder ExceptTime()
        {
            return ExceptField("time");
        }

        public MatchPlayerStatsAllTalkEventTypeQueryBuilder WithMessage(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("message", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsAllTalkEventTypeQueryBuilder ExceptMessage()
        {
            return ExceptField("message");
        }

        public MatchPlayerStatsAllTalkEventTypeQueryBuilder WithPausedTick(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("pausedTick", alias, new GraphQlDirective[] { include, skip });
        }

        public MatchPlayerStatsAllTalkEventTypeQueryBuilder ExceptPausedTick()
        {
            return ExceptField("pausedTick");
        }
    }
}
