// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum MatchPlayerRoleType
    {
        [EnumMember(Value = "CORE")] Core,
        [EnumMember(Value = "LIGHT_SUPPORT")] LightSupport,
        [EnumMember(Value = "HARD_SUPPORT")] HardSupport,
        [EnumMember(Value = "UNKNOWN")] Unknown
    }
}
