// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchLiveInsightType
    {
        public int? TeamOneVsWinCount { get; set; }
        public int? TeamTwoVsWinCount { get; set; }
        public int? TeamOneLeagueWinCount { get; set; }
        public int? TeamOneLeagueMatchCount { get; set; }
        public int? TeamTwoLeagueWinCount { get; set; }
        public int? TeamTwoLeagueMatchCount { get; set; }
        public IList<SeriesType> LastSeries { get; set; }
    }
}
