// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class MatchReplayUploadMatchType
    {
        public long? MatchUploadTeamId { get; set; }
        public long? Id { get; set; }
        public string FileName { get; set; }
        public object UploaderCaptainJackIdentityId { get; set; }
        public bool? IsValidated { get; set; }
        public bool? IsComplete { get; set; }
        public bool? IsActive { get; set; }
        public bool? DidRadiantWin { get; set; }
        public short? DurationSeconds { get; set; }
        public int? DurationMinutes { get; set; }
        public DateTime? StartDateTime { get; set; }
        public DateTime? EndDateTime { get; set; }
        public byte? LobbyType { get; set; }
        public byte? NumHumanPlayers { get; set; }
        public byte? NumHumanSpectators { get; set; }
        public int? LeagueId { get; set; }
        public long? SeriesId { get; set; }
        public byte? GameMode { get; set; }
        public int? RadiantTeamId { get; set; }
        public byte? RadiantKills { get; set; }
        public int? DireTeamId { get; set; }
        public byte? DireKills { get; set; }
        public bool? IsRadiantFirstPick { get; set; }
        public int? GameVersionId { get; set; }
        public string Notes { get; set; }
        public IList<MatchReplayUploadPlayerType> Players { get; set; }
        public IList<object> Spectators { get; set; }
        public IList<MatchReplayUploadPickBanType> PickBans { get; set; }
        public TeamType RadiantTeam { get; set; }
        public TeamType DireTeam { get; set; }
        public LeagueType League { get; set; }
    }
}
