// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlayerHeroDotaPlusLeaderboardRankResponseTypeQueryBuilder : GraphQlQueryBuilder<PlayerHeroDotaPlusLeaderboardRankResponseTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "players", IsComplex = true, QueryBuilderType = typeof(HeroDotaPlusLeaderboardRankTypeQueryBuilder) }
            };

        protected override string TypeName { get { return "PlayerHeroDotaPlusLeaderboardRankResponseType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public PlayerHeroDotaPlusLeaderboardRankResponseTypeQueryBuilder WithPlayers(HeroDotaPlusLeaderboardRankTypeQueryBuilder heroDotaPlusLeaderboardRankTypeQueryBuilder, string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithObjectField("players", alias, heroDotaPlusLeaderboardRankTypeQueryBuilder, new GraphQlDirective[] { include, skip });
        }

        public PlayerHeroDotaPlusLeaderboardRankResponseTypeQueryBuilder ExceptPlayers()
        {
            return ExceptField("players");
        }
    }
}
