// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlayerBattlePassGroupByType
    {
        public string Id { get; set; }
        public long? PlayerCount { get; set; }
        public long? SumLevels { get; set; }
        public long? PlayerCountAt { get; set; }
    }
}
