// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class PlusHeroTeamStatusAveragesType
    {
        public decimal? Cs { get; set; }
        public decimal? Deaths { get; set; }
        public decimal? TowerDamage { get; set; }
        public decimal? PhysicalDamage { get; set; }
        public decimal? MagicalDamage { get; set; }
        public decimal? PhysicalDamageReceived { get; set; }
        public decimal? MagicalDamageReceived { get; set; }
        public decimal? DisableCount { get; set; }
        public decimal? DisableDuration { get; set; }
        public decimal? StunCount { get; set; }
        public decimal? StunDuration { get; set; }
        public decimal? SlowCount { get; set; }
        public decimal? SlowDuration { get; set; }
        public decimal? HealingAllies { get; set; }
        public decimal? PurgeModifiers { get; set; }
        public decimal? WeakenCount { get; set; }
        public decimal? WeakenDuration { get; set; }
        public decimal? PureDamageReceived { get; set; }
        public decimal? PureDamage { get; set; }
    }
}
