// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum RuneEnums
    {
        [EnumMember(Value = "HASTE")] Haste,
        [EnumMember(Value = "REGEN")] Regen,
        [EnumMember(Value = "DOUBLE_DAMAGE")] DoubleDamage,
        [EnumMember(Value = "ILLUSION")] Illusion,
        [EnumMember(Value = "INVISIBILITY")] Invisibility,
        [EnumMember(Value = "BOUNTY")] Bounty,
        [EnumMember(Value = "ARCANE")] Arcane,
        [EnumMember(Value = "WATER")] Water
    }
}
