// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public enum TableCalculateEnum
    {
        [EnumMember(Value = "AVERAGE")] Average,
        [EnumMember(Value = "MEDIAN")] Median,
        [EnumMember(Value = "HIGHEST")] Highest,
        [EnumMember(Value = "LOWEST")] Lowest
    }
}
