// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace STRATZ
{
    public partial class TotalPlayerCountTypeQueryBuilder : GraphQlQueryBuilder<TotalPlayerCountTypeQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
                new FieldMetadata { Name = "playerCount", IsComplex = true }
            };

        protected override string TypeName { get { return "TotalPlayerCountType"; } } 

        public override IReadOnlyList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public TotalPlayerCountTypeQueryBuilder WithPlayerCount(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("playerCount", alias, new GraphQlDirective[] { include, skip });
        }

        public TotalPlayerCountTypeQueryBuilder ExceptPlayerCount()
        {
            return ExceptField("playerCount");
        }
    }
}
